container:
    image: node:latest
    memory: 8G

check_task:
    node_modules_cache:
        folder: node_modules
        fingerprint_script: cat yarn.lock
        populate_script: yarn install

    test_script: yarn ci
