image: node:11.15.0

cache:
    paths:
        - node_modules/
        - .yarn

stages:
    - test

test:
    stage: test

    before_script:
        - apt-get update
        - apt-get install -y protobuf-compiler
        - apt-get install -y libprotobuf-dev
        - yarn config set cache-folder .yarn
        - yarn install

    script:
        - yarn lint
        - yarn test
        - yarn build

    only:
        - master
        - merge_requests
