[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"
CI = "1"
DEBUG = "netlify-plugin-cypress,netlify-plugin-cypress:verbose"

# Set the HEDERA_NETWORK to mainnet for production
[context.production.environment]
HEDERA_NETWORK = "mainnet"

# Set the HEDERA_NETWORK to testnet for deployment previews on PRs
[context.deploy-preview.environment]
HEDERA_NETWORK = "testnet"

# Redirect all access to / as this is a Single Page Application
[[redirects]]
from = "/*"
to = "/"
status = 200

[[plugins]]
package = "netlify-plugin-cypress"

# [plugins.inputs.preBuild]
# start = "yarn serve:test"
# wait-on = 'http://localhost:8080'
# wait-on-timeout = '120' # seconds